27-09-2024edited — копия/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += [
    path('', include('store.urls'), name='store'),
    path('users/', include('users.urls'), name='users'),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

27-09-2024edited — копия/store/urls.py
from django.urls import path

from .views import MainPageView

app_name = "store"

urlpatterns = [
    path("", MainPageView.as_view(), name="mainpage"),
    # path("books/", views.BookListView.as_view(), name="books"),
    # path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
]

27-09-2024edited — копия/users/urls.py
from django.urls import path
from .views import UserProfileView, register, login_view, logout_view

app_name = "users"

urlpatterns = [
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

27-09-2024edited — копия/orders/models.py
from django.contrib.auth.models import User
from django.db import models
from vinyls.models import VinylRecord

class Basket(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    vinyl_records = models.ManyToManyField(VinylRecord)

    def __str__(self):
        return f"Корзина пользователя {self.user.username}"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vinyl_records = models.ManyToManyField(VinylRecord)
    created_at = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"Заказ №{self.id} от {self.user.username}"

27-09-2024edited — копия/store/models.py
from django.db import models

# Create your models here.

27-09-2024edited — копия/users/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio=models.TextField(null=True, blank=True)
    pic = models.ImageField(null=True, blank=True, upload_to="images/profile/")
    insta = models.textField(User, null=True, on_delete=models.Model)
def __str__(self):
    return str(self.user)

27-09-2024edited — копия/vinyls/models.py
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class VinylRecord(models.Model):
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    audio_file = models.FileField(upload_to='vinyl_audio/')
    tags = models.ManyToManyField(Tag, related_name='records')

    def __str__(self):
        return f"{self.title} - {self.artist}"

27-09-2024edited — копия/users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "email", "password"]

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Пароли не совпадают.")


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

27-09-2024edited — копия/orders/views.py
from django.shortcuts import render

# Create your views here.

27-09-2024edited — копия/store/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView

class MainPageView(TemplateView):
    template_name = "mainpage/index.html"

27-09-2024edited — копия/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from .forms import UserRegistrationForm, UserLoginForm

from orders.models import Order

class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(user=self.request.user)
        return context


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('user_profile')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('user_profile')
    else:
        form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('users:login')

27-09-2024edited — копия/vinyls/views.py
from django.shortcuts import render

# Create your views here.

27-09-2024edited — копия/templates/base/base.html
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        <div id="header">
            <h1>{% block header %}{% endblock %}</h1>
        </div>
        <div id="nav">
            {% block nav %}{% include './nav.html' %}{% endblock %}
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <div id="footer">
            {% block footer %}{% endblock %}
        </div>
    </body>
</html>

27-09-2024edited — копия/templates/base/nav.html
<nav>
    <a href="/">Home</a>
    <a href="{% url 'users:user_profile' %}">Profile</a>
    <a href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:login' %}">Login</a>
    <a href="{% url 'users:logout' %}">Logout</a>

    {% comment %}
    <a href="{% url 'about' %}">About</a>
    <a href="{% url 'contact' %}">Contact</a>
    <a href="{% url 'admin:index' %}">Admin</a>
    <a href="{% url 'store' %}">Store</a>
    <a href="{% url 'cart' %}">Cart</a>
    <a href="{% url 'checkout' %}">Checkout</a>
    <a href="{% url 'register' %}">Register</a>
    <a href="{% url 'login' %}">Login</a>
    <a href="{% url 'logout' %}">Logout</a>
    {% endcomment %}
</nav>

27-09-2024edited — копия/templates/mainpage/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Main Page</h1>
{% endblock %}

27-09-2024edited — копия/templates/users/login.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Регистрация</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock content %}

27-09-2024edited — копия/templates/users/profile.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Profile</h1>
{% endblock %}

27-09-2024edited — копия/templates/users/register.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Регистрация</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
    </form>
{% endblock content %}

27-09-2024edited — копия/templates/users/user_profile.html
{% block content %}

    <div class="header-bar">
        <h1>Profile</h
        
        <a href="{% url 'tasks' %}">&#8592; Back</a>
        
    </div>
    
    {% if user.profile.profile_pic %}
       <a href="{% url 'edit_user_profile' profile.id %}"><button class="button">Edit</button></a>
    {%else%}
      <img src="{% static '\images\profile\user.png' %}" height=100 width=100><br><br>
    {% if user.id == profile.user.id %}
      {% endif %}
      
    
    
    </div>

{% endblock content %}